//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CourseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CourseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRK.CourseResources", typeof(CourseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {script:&quot;Ext.net.replaceContent(win_17,\&quot;win_17_Content\&quot;,[\&quot;&lt;div id=\\\&quot;win_17_Content\\\&quot; class=\\\&quot;x-hidden\\\&quot;&gt;\&quot;,\&quot;&lt;div&gt;\&quot;,\&quot;&lt;table cellspacing=\\\&quot;0\\\&quot; cellpadding=\\\&quot;3\\\&quot; rules=\\\&quot;cols\\\&quot; id=\\\&quot;cont_win_17_GridView1\\\&quot; style=\\\&quot;color:Black;background-color:White;border-color:#999999;border-width:1px;border-style:Solid;border-collapse:collapse;\\\&quot;&gt;\&quot;,\&quot;&lt;tr style=\\\&quot;color:White;background-color:Black;font-weight:bold;\\\&quot;&gt;\&quot;,\&quot;&lt;th scope=\\\&quot;col\\\&quot;&gt;id&lt;/th&gt;&lt;th scope=\\\&quot;col\\\&quot;&gt;Code&lt;/th&gt;&lt;th sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbeddedList {
            get {
                return ResourceManager.GetString("EmbeddedList", resourceCulture);
            }
        }
    }
}
